name: Build and Deploy containers

on:
  # Always test on pull request
  pull_request: []

  # Deploy on merge to main
  push:
    branches:
      - main

jobs:
  deploy-test-containers:
    runs-on: ubuntu-latest
    name: Build Container
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Container
        run: |
            docker build -t ghcr.io/tunel-apps/tunel-django .
            version=$(cat VERSION)
            docker tag ghcr.io/tunel-apps/tunel-django:latest ghcr.io/tunel-apps/tunel-django:${version}

      - name: Login and Deploy Test Container
        if: (github.event_name != 'pull_request')
        run: |
            docker images
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            version=$(cat VERSION)
            docker push ghcr.io/tunel-apps/tunel-django:latest
            docker push ghcr.io/tunel-apps/tunel-django:${version}
