name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup black environment
        run: conda create --quiet --name black black

      - name: Check formatting with black
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          black --check tuneldjango

  testing:
    needs: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup testing environment
        run: conda create --quiet --name testing

      - name: Test tunel-django
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate testing
          pip install -r requirements.txt
          export DJANGO_SECRET_KEY=thiskeyisnotsosecret
          python manage.py test tests.test_project
